# Generated by Django 2.1.7 on 2019-04-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_case'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='Case',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.case'),
        ),
        migrations.AlterField(
            model_name='config',
            name='CPU',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='products.CPU'),
        ),
    ]
