# Generated by Django 2.1.7 on 2019-04-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190407_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпусы для ПК'},
        ),
    ]
